apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "k8s-crondash.name" . }}
  labels:
    {{- include "k8s-crondash.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: {{ .Values.env.listenAddr | quote }}
  NAMESPACE: {{ include "k8s-crondash.resolveNamespace" . | quote }}
  REFRESH_INTERVAL: {{ .Values.env.refreshInterval | quote }}
  JOB_HISTORY_LIMIT: {{ .Values.env.jobHistoryLimit | quote }}
