{{- include "k8s-crondash.replicaGuard" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "k8s-crondash.name" . }}
  labels:
    {{- include "k8s-crondash.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "k8s-crondash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-crondash.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-crondash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ include "k8s-crondash.name" . }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "k8s-crondash.name" . }}
            - secretRef:
                name: {{ include "k8s-crondash.name" . }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
