{{- if and .Values.rbac.create (ne .Values.env.namespace "") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-crondash.name" . }}
  namespace: {{ include "k8s-crondash.resolveNamespace" . }}
  labels:
    {{- include "k8s-crondash.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "k8s-crondash.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-crondash.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
