apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "k8s-crondash.name" . }}
  labels:
    {{- include "k8s-crondash.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_USERNAME: {{ .Values.auth.username | required "auth.username is required" | quote }}
  AUTH_PASSWORD: {{ .Values.auth.password | required "auth.password is required" | quote }}
