apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "k8s-crondash.serviceAccountName" . }}
  labels:
    {{- include "k8s-crondash.labels" . | nindent 4 }}
automountServiceAccountToken: true
