replicaCount: 1

image:
  repository: ghcr.io/acidghost/k8s-crondash
  tag: latest@sha256:1eb7330269efbd025b56fa6dae0cb1e099063b41ed7892ca749c4ad24ca8abb0
  pullPolicy: Always

service:
  port: 3000

rbac:
  create: true

auth:
  username: ""
  password: ""

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

env:
  listenAddr: ":3000"
  namespace: "-"
  refreshInterval: "5"
  jobHistoryLimit: "5"

ingress:
  enabled: false
  className: ""
  hosts: []
  #   - host: k8s-crondash.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls: []
  #   - secretName: k8s-crondash-tls
  #     hosts:
  #       - k8s-crondash.example.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /readyz
    port: 3000
  periodSeconds: 10
  initialDelaySeconds: 5
