name: Publish Chart

on:
  workflow_dispatch:
    inputs:
      registry:
        description: "Container registry URL"
        required: false
        default: "ghcr.io"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

env:
  # renovate: datasource=github-releases depName=jdx/mise
  MISE_VERSION: 2026.7.7

jobs:
  publish-chart:
    name: Publish Chart
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # needed to push helm chart
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          version: ${{ env.MISE_VERSION }}

      - name: Log in to registry
        run: helm registry login "${INPUTS_REGISTRY}" --username "${GITHUB_ACTOR}" --password "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUTS_REGISTRY: ${{ inputs.registry }}

      - run: just helm-push
